---
abstract: 'Punycode conversion of UTF-8 string.'
author:
  - 'Twinkle Computing <twinkle@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-UTF8-Punycode
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.97
