--- #YAML:1.0
name:                URI-UTF8-Punycode
version:             0.96
abstract:            Punycode conversion of UTF-8 string.
license:             GPL_3
author:              
    - Twinkle Computing <twinkle@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
